version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.4
    environment:
      GOPATH: /home/circleci/project/go
    working_directory: /home/circleci/project/go
    steps:
      - checkout
      - run:
          command: go get github.com/astaxie/beego
      - run:
          command: cd weather && go build
workflows:
  version: 2
  workflow:
    jobs:
    - build
