version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.10.4
    working_directory: /go/src/github.com/makecodexyz/weather
    steps:
    - checkout
    - run:
        command: go get github.com/astaxie/beego
    - run:
        command: go build
workflows:
  version: 2
  workflow:
    jobs:
    - build
